# Generated by Django 2.2.3 on 2019-07-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('is_admin', 'Is Admin'), ('is_manager', 'Is Manager'), ('is_agent', 'Is Agent'))},
        ),
    ]
